### ISSUE TITLE
Cannot register twice

### ISSUE THREAD

**Issue by SilverComet89** [akilli/rte#1]
I've been trying to use this plugin, but after compiling as soon as I load the page the following error stops ckeditor from loading:

`Error: schema-cannot-register-item-twice: A single item cannot be registered twice in the schema. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-schema-cannot-register-item-twice {"itemName":"media"}`

**Comment by akilli** [comment]
This is no plugin, this is just a

> Rich text editors test setup

for the demos
